Feature/sprint 07
fev0ks/ydx-goadv-metrics pull request #7
Opened 2023-03-07 17:18 UTC by fev0ks

Собрал какой-то профайлер
Отформатировал импорты
Добавил немного документации как результат ознакомления с материалом

2023-03-08 19:50 UTC, kilchik requested changes
Для закрепления материала (по заданию из инкемента 15) нужно попробовать добавить бенчмарк для какой-то потенциально оптимизируемой функции (как описано в главе "Бенчмарки") и попробовать ее соптимизировать

2023-03-08 19:50 UTC, kilchik commented on cmd/server/rest/metric_handler_test.go
> +// Добавьте примеры работы с эндпоинтами практического трека в формате - втф?
Тут нужно добавить пример по аналогии с example_test из инкремента 17 так, чтобы он потом оказался в сгенерированной godoc документации. Это может быть любой пример, демонстрирующий работу с каким-то хендлером или функцией.

2023-03-09 07:38 UTC, fev0ks commented
* was added benchmark - BenchmarkCommonRepository_SaveMetrics;
* some doc examples provided for  server commonRepository
![image](https://user-images.githubusercontent.com/25535739/223952619-6b245311-0648-4e65-a28f-7b364c6fdef3.png)

2023-03-09 12:05 UTC, kilchik approved these changes

2023-03-09 13:05 UTC, merged